language: go

go:
- 1.6

before_install:
- wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.40.zip
- unzip go_appengine_sdk_*.zip
- pwd
- env
- ls
- find .

install:
- goapp get .
- goapp build

script:
- true
